baseURL = "https://peaceful-edison-270270.netlify.com"
languageCode = "en-us"
title = "Skylup"
theme = "journal"

[params]
	description = "Blog meta description."
	githubUsername = "skatkov"
	twitterUsername = "5katkov"
	tagline = "A dream will always triumph over reality , once it is given a chance..."
